# docker-compose.prod.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '5005:5005'
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/SafeRoad-back
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
